# Generated by Django 5.0.6 on 2024-05-29 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campagin', '0001_initial'),
        ('center', '0001_initial'),
        ('vaccin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaing',
            name='agents',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaing',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center'),
        ),
        migrations.AddField(
            model_name='campaing',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccin.vaccine'),
        ),
        migrations.AddField(
            model_name='slot',
            name='campaing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campagin.campaing'),
        ),
    ]
